### ISSUE TITLE
Which slugify version was this?

### ISSUE THREAD

**Issue by elioscordo** [anthonyjb/box51#2]
https://github.com/anthonyjb/box51/blob/c9b11eba1a35d58a44adfd896db818101b2408e5/box51/__init__.py#L8

**Comment by anthonyjb** [comment]
So Box51 is designed to run under manhattan which was previously using `awesome-slugify` over the last few days we became aware of a recent conflict between `awesome-slugify` and `python-slugify` and decided to move to `python-slugify` as the better supported library.

I need to update box51 inline with this change (just haven't gotten around to it as we yes H51 internally) but I'll do that now (give me 30 minutes).

**Comment by anthonyjb** [comment]
@elioscordo library is now update to release 0.2.0 which swtiches box51 to use python-slugify making it compatible with Manhattan again.

**Comment by elioscordo** [comment]
Thank you so much. We are pulling the project using pip 
box51==0.1.3
any change we can this change through pip as well?

**Comment by anthonyjb** [comment]
If you pull develop down that now has 0.2.0 in the requirements.txt (that's all that needed changing). However, I just let Mate know for the project we're working on we're using H51 because it has face and feature detection requirements which aren't supported by box51 unfortunately (I do mean to get around to adding them).

**Comment by elioscordo** [comment]
I bumped into the issue  just running the project (fab start) with the basic configuration. The patch worked. Let us know if you drop the dependency, it is not urgent though.
